 events {}

http {
    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth-service:8000/;
        }

        location /user/ {
            proxy_pass http://user-service:8000/;
        }

        location /project/ {
            proxy_pass http://project-service:8000/;
        }

        location /task/ {
            proxy_pass http://task-service:8000/;
        }

        location /uat/ {
            proxy_pass http://uat-service:8000/;
        }

        location /ai/ {
            proxy_pass http://ai-service:8000/;
        }

        location /file/ {
            proxy_pass http://file-service:8000/;
        }

        location /notification/ {
            proxy_pass http://notification-service:8000/;
        }
    }
}

